name: add-two-numbers
version: 0.1.0

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  add-two-numbers-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - add-two-numbers

tests:
  add-two-numbers-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - add-two-numbers
      - hspec
