name: mini-typechecker
version: 0.1.0

dependencies:
  - base >= 4.7 && < 5
  - containers

library:
  source-dirs: src

executables:
  mini-typechecker-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - mini-typechecker

tests:
  mini-typechecker-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - mini-typechecker
      - hspec
